export const SILO_PAGES = [
  // 12 Tier 1 Money Pages
  "flower-bouquets-bahrain",
  "gift-delivery-bahrain",
  "flowers-and-cake-delivery-bahrain",
  "flowers-and-chocolates-delivery-bahrain",
  "flowers-cake-and-chocolates-bahrain",
  "same-day-gift-delivery-bahrain",
  "birthday-gifts-delivery-bahrain",
  "online-gift-shop-bahrain",

  // Foundation Pages 
  "same-day-delivery-bahrain",
  "express-delivery-bahrain",
  "delivery-areas-bahrain",
  "corporate-gifts-bahrain",

  // Main commercial categories (excluding duplicates from Tier 1)
  "hand-bouquets-bahrain",
  "rose-bouquets-bahrain",
  "gift-boxes-bahrain",
  "gift-hampers-bahrain",
  "balloons-delivery-bahrain",
  "perfume-gifts-bahrain",
  "plants-delivery-bahrain",

  // Combo / bundle pages
  "flowers-and-balloons-bahrain",
  "flowers-and-gifts-bahrain",
  "cake-and-chocolates-bahrain",
  "gift-box-with-flowers-bahrain",
  "gift-box-with-cake-bahrain",
  "gift-box-with-chocolates-bahrain",
  "money-bouquet-bahrain",
  "money-box-gifts-bahrain",
  "flower-box-bahrain",
  "flower-vase-arrangements-bahrain",
  "premium-gift-baskets-bahrain",
  "custom-gifts-bahrain",
  "personalized-gifts-bahrain",

  // Occasion pages
  "birthday-flowers-bahrain",
  "birthday-cakes-bahrain",
  "birthday-gifts-bahrain",
  "birthday-flowers-and-cake-bahrain",
  "anniversary-flowers-bahrain",
  "anniversary-gifts-bahrain",
  "graduation-bouquets-bahrain",
  "graduation-gifts-bahrain",
  "newborn-gifts-bahrain",
  "new-baby-flowers-bahrain",
  "get-well-soon-flowers-bahrain",
  "sympathy-flowers-bahrain",
  "thank-you-flowers-bahrain",
  "love-and-romantic-gifts-bahrain",
  "mothers-day-flowers-bahrain",
  "valentines-day-flowers-bahrain",
  "eid-gifts-bahrain",
  "ramadan-gifts-bahrain",
  "wedding-gifts-bahrain",
  "housewarming-gifts-bahrain",

  // Location pages
  "flower-delivery-manama",
  "gift-delivery-manama",
  "cake-delivery-manama",
  "flower-delivery-riffa",
  "gift-delivery-riffa",
  "cake-delivery-riffa",
  "flower-delivery-muharraq",
  "gift-delivery-muharraq",
  "flower-delivery-isa-town",
  "flower-delivery-adliya",
  "flower-delivery-seef",
  "flower-delivery-juffair",
  "flower-delivery-saar",
  "flower-delivery-hamala",
  "flower-delivery-amwaj",
  "flower-delivery-diyar-al-muharraq",
  "flower-delivery-budaiya",
  "flower-delivery-sanabis",

  // Product subtypes
  "red-roses-bahrain",
  "white-roses-bahrain",
  "tulip-bouquets-bahrain",
  "orchid-arrangements-bahrain",
  "lily-bouquets-bahrain",
  "sunflower-bouquets-bahrain",
  "chocolate-boxes-bahrain",
  "ferrero-rocher-gifts-bahrain",
  "luxury-chocolates-bahrain",
  "bento-cakes-bahrain",
  "chocolate-cakes-bahrain",
  "red-velvet-cakes-bahrain",
  "mini-cakes-bahrain",
  "helium-balloons-bahrain",
  "gift-baskets-bahrain",
  "flower-baskets-bahrain",
  "luxury-perfume-gifts-bahrain",
  "indoor-plants-bahrain",

  // Buying Intent / Query match
  "cheap-flower-delivery-bahrain",
  "luxury-flower-delivery-bahrain",
  "best-flower-shop-in-bahrain",
  "best-online-gift-shop-bahrain",
  "same-day-cake-delivery-bahrain",
  "same-day-chocolate-delivery-bahrain",
  "midnight-gift-delivery-bahrain",
  "last-minute-gifts-bahrain",
  "order-flowers-online-bahrain",
  "send-gifts-to-bahrain-from-abroad",

  // Link Support / Authority content
  "best-flowers-for-birthday-gifts",
  "best-gift-ideas-in-bahrain",
  "how-to-choose-a-flower-bouquet",
  "same-day-delivery-guide-bahrain",
  "gift-guide-for-every-occasion-bahrain",
  "flowers-vs-chocolates-vs-cakes-best-gift-guide",

  // Core Platform Pages (Fixing 404 Navigation Errors)
  "contact-us",
  "about-us",
  "faq",
  "privacy-policy",
  "terms-of-service"
];
